<<<<<<< HEAD
# Generated by Django 2.1.3 on 2018-11-23 08:17
=======
# Generated by Django 2.0.3 on 2018-11-27 12:18
>>>>>>> 6e6a9906ffb081845cea9f1376ae9919dcce4827

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('shop', '0001_initial'),
        ('coupons', '0001_initial'),
=======
        ('coupons', '0001_initial'),
        ('shop', '0001_initial'),
>>>>>>> 6e6a9906ffb081845cea9f1376ae9919dcce4827
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
=======
                ('phone', models.CharField(max_length=50)),
                ('wechat', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
>>>>>>> 6e6a9906ffb081845cea9f1376ae9919dcce4827
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.Coupon')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product')),
            ],
        ),
    ]
